version: '3.6'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress2
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$MARIADB_USER
      - WORDPRESS_DB_PASSWORD=$MARIADB_PASSWORD
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 8081:80

  db:
    image: mariadb:latest
    container_name: db2
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin2
    restart: always
    ports:
      - 8181:80
    env_file: .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD

volumes:
  db_data:
